name: Compile vterron.xyz/forty Beamer slides to PDF

on: [push]

env:
  BASENAME: forty-features
  WORKING_DIR: "[2013] Forty Features of Python that You May Not Know"

jobs:
  build_job:
    name: Build PDF slides
    runs-on: ubuntu-latest

    steps:
      - name: Git repository checkout
        uses: actions/checkout@v2

      - name: LaTeX compilation
        uses: dante-ev/latex-action@master
        with:
          root_file: ${{ env.BASENAME }}.tex
          working_directory: ${{ env.WORKING_DIR }}

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: slides-pdf
          # The path hierarchy is preserved after the first wildcard pattern.
          path: "**/${{ env.BASENAME }}.pdf"

  upload_job:
    name: Upload PDF slides
    needs: build_job
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download PDF artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: slides-pdf

      - name: Upload PDF slides to Amazon S3
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          aws s3 cp ${{ env.BASENAME }}.pdf ${{ secrets.AWS_S3_BUCKET }}
